// "use client"
import type { Metadata } from "next";
import {  Inter,Poppins } from "next/font/google";
import "./globals.css";
import { SettingsProvider } from "./context/SettingContext";
import { Header } from "./components/Header";

// Configure the fonts
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Assign a CSS variable
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Load specific weights
  variable: '--font-poppins', // Assign a CSS variable
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayouts({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable}${poppins.variable}  antialiased`}
      >
        <SettingsProvider>
          <Header />x

       
        {children}
        </SettingsProvider>
      </body>
    </html>
  );
}


// import { useState } from "react";

// export default function SettingsCard() {
//   const [isOpen, setIsOpen] = useState(false);

//   return (
//     <div className="relative">
//       {/* Settings Button */}
//       <button
//         onClick={() => setIsOpen(!isOpen)}
//         className="fixed top-4 right-4 p-2 bg-blue-500 text-white rounded-lg shadow-md hover:bg-blue-600"
//       >
//         Settings
//       </button>

//       {/* Settings Card */}
//       <div
//         className={`fixed top-0 right-0 h-full w-80 bg-white shadow-lg border-l transform transition-transform duration-300 ease-in-out ${
//           isOpen ? "translate-x-0" : "translate-x-full"
//         }`}
//       >
//         <div className="p-4">
//           <h2 className="text-lg font-semibold">Settings</h2>
//           <p className="mt-2 text-gray-600">Manage your preferences here.</p>
//           {/* Add your settings content here */}
//           <button
//             onClick={() => setIsOpen(false)}
//             className="mt-4 p-2 bg-red-500 text-white rounded-md shadow hover:bg-red-600"
//           >
//             Close
//           </button>
//         </div>
//       </div>

//       {/* Overlay (optional, to close settings on click outside) */}
//       {isOpen && (
//         <div
//           className="fixed inset-0 bg-black bg-opacity-30"
//           onClick={() => setIsOpen(false)}
//         ></div>
//       )}
//     </div>
//   );
// }
